---
title: "An Analysis of Storms and Severe Weather Events on the United States's Population Health and Economy (1950 - 2011)"
output: html_document
---

###Abstract  

###Data Processing    
1.  Clear the screen and load the required libraries
```{r}
rm(list=ls())   #Clear all objects

require(dplyr)
require(stringr)
require(ggplot2)
require(knitr)
```
2.  Set the working directory and file vectors
```{r}
working.dir <- "C://Education//Reproducible Research//Homework//Peer Assessment 2"
setwd(working.dir)

input.dir <- ".\\input\\"
output.dir <- ".\\output\\"
script.dir <- ".\\scripts\\"
input.storm.data <- "repdata-data-StormData.csv"
input.storm.ref.data <- "storm-reference-data.csv"
```
3.  Load the storm data
```{r, cache = TRUE}
storm.data <- read.csv(paste(input.dir, input.storm.data, sep="\\"), stringsAsFactors = FALSE, strip.white = TRUE)
storm.ref.data <- read.csv(paste(input.dir, input.storm.ref.data, sep="\\"), stringsAsFactors = FALSE, strip.white = TRUE)
```
4.  Subeset storm.data where pop.health > 0 | PROPDMG > 0 | CROPDMG > 0
```{r, cache = TRUE}
storm.data.step.1 <- storm.data %.%
  mutate(pop.health = FATALITIES + INJURIES, 
         prop.dmg.exp = 0,
         prop.dmg.value = 0,
         crop.dmg.exp = 0,
         crop.dmg.value = 0,
         total.dmg.value = 0,
         event.type.id = as.integer(0)) %.%
  select(event.type.id, EVTYPE, FATALITIES, INJURIES, pop.health, PROPDMG, PROPDMGEXP, prop.dmg.exp, prop.dmg.value, CROPDMG, CROPDMGEXP, crop.dmg.exp, crop.dmg.value, total.dmg.value) %.%
  filter(pop.health > 0 | PROPDMG > 0 | CROPDMG > 0)
```

5.  Clean-up the subsetted data
```{r}
storm.data.step.1$PROPDMGEXP = toupper(storm.data.step.1$PROPDMGEXP)
storm.data.step.1$CROPDMGEXP = toupper(storm.data.step.1$CROPDMGEXP)
storm.data.step.1$EVTYPE <- str_trim(storm.data.step.1$EVTYPE)
```

###Results    
